### PR TITLE
Create FullNotes

### PR DESCRIPTION
**Pull request by jbaltziii**

### CODE REVIEW

**Comment by sux13** [comment]
Was this submitted in error?

**Comment by jbaltziii** [comment]
Yes - still learning, sorry

**Comment by sux13** [comment]
No worries. Here's a guide on how to use github (http://rogerdudler.github.io/git-guide/). Cheers.

**Comment by jbaltziii** [comment]
Lol
Yeah - I need it - and to watch the videos that I found.

Learning curve slope is > right now....
Many thanks

**Pull request closed without merging**
