### PR TITLE
Add convenience binder (PDF).

### PR DESCRIPTION
**Pull request by stepds**
Hi Xing, this is simply a combined PDF file with a cover page added of the single-class PDF files you authored. Main advantages: all-in-one convenience and the cover page with live links to sub-sections. Main disadvantage: this binder might not track future updates closely.
Anyway, take it or leave it as you see fit. Thanks for sharing your masterwork!

### CODE REVIEW

**Comment by sux13** [comment]
Hey, thanks so much for putting work in this. I think that while having one file is convenient, you would still have to scroll to the subsections for each course to find content, which is effective what the website is for. In addition, we would have to manually update the file for every update that we make to the master file, which I think would be incredibly painful and we might run into discrepancies between files. What do you think?

**Comment by stepds** [comment]
Sure I agree, PDF offers little/no convenience when a website is available. A PDF binder can increase convenience primarily for offline viewing, that's it. And manually updating the binder is necessary when new PDFs are generated. Mmm, I wonder, were you able to read my introductory comment, which touches exactly on this last point?
Anyway, I put this binder together for my own convenience; I do not think that it is essential to your package in any way. A binder is more convenient when (a) one need to use PDF, and (b) one plans to jump from class to class or search across classes.
As this binder stands now, internal links allow navigating cover to class index (and back), and class index to class sub-sections (no back link, though).
Of course, generating a PDF binder with cover by using R/knitr directly rather than by pasting PDFs together would be a better solution.

**Comment by sux13** [comment]
I did read your comments and I apologize if it came across as I'm not paying attention.

I do agree there's merit in combining all of the content to allow for searching across classes. I'm actually working on implementing a search bar directly on the website for people to use to query content. 

As for the PDF, I'm a bit hesitant only because it would cause versioning problems. If you take a look at folders in the repo for the last three classes, I actually have two versions of the .Rmd file: one for HTML and one for PDF. That's because somethings only work on PDF and won't render correctly on the HTML. These two versions of the same file is already causing me a lot of headaches as I correct minor errors on the documents themselves. Having to do for the aggregate file would be even more painful. 

I'll look for a way for generating multiple documents through one .Rmd file and hopefully we can just keep all the code in one place, that way I can update everything at once. 

Let me know what your thoughts are.

**Comment by stepds** [comment]
I think you're spot on wanting to avoid multiple versioning. And now, with better judgement, I can see that making a PDF binder is premature. It should wait until the .Rmd files are stable and free from typos/errors.

**Comment by sux13** [comment]
Thanks for the support anyway. Please feel free to send me more pull requests. It's literally over 300 pages of content. I tried my best to correct typos and silly mistakes, but i'm sure there are plenty in there. I could definitely use additional examples for some of it. To be honest, I had to stop myself from working on it any more after 2 weeks because it can literally be endless. That's why I opened it to the community as well. Cheer.s

**Pull request closed without merging**
